import { useEffect, useRef, useState } from 'react'
import moment from 'moment';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import Overlay from 'react-bootstrap/Overlay'
import Tooltip from 'react-bootstrap/Tooltip'

import Datetime from 'react-datetime'

import ImageMarker from 'react-image-marker';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faLocationPin } from '@fortawesome/free-solid-svg-icons'

import axios from 'axios';

function DeathTip({ death }) {
  const target = useRef(null);

  return (<div>
  <div
    ref={target}
    style={{
      position: 'absolute',
      bottom: `calc(100% * (1 - ${death.pin.y}))`,
      left: `calc(100% * (${death.pin.x}))`
  }}

  >
    </div>
  <Overlay show={true} target={target.current} shouldUpdatePosition={true} key={Math.random()}>
  <Tooltip>
  {death.desc}
  </Tooltip>
  </Overlay>
    </div>);
}

function Map({ name, death }) {

  const [ marker, setMarkers ] = useState([]);

  const src = '/maps/' + name + '.png';

  return (
    <div className={styles.mapdiv}>
      <img src={src} className={styles.map}/>
      {(death && <DeathTip death={death} />)}
    </div>
  );
}

function DeathForm({ deaths }) {
  const [ index, setIndex ] = useState(0);
  console.log('On death', index);

  const maps = [ 'overworld', 'underworld' ];

  const dateFormat = "YYYY-MM-DD";
  const timeFormat = "hh:mm:ss A";
  const formatTime = (t) => moment(t).format(dateFormat + " " + timeFormat);

  const death = (index < deaths.length && deaths[index]);
  const map = (death && death.map) || 'overworld';

  return (
    <div>
      <Form.Range id='index' value={index} onChange={(e) => setIndex(e.target.value)} min={0} max={deaths.length-1}/>
        <Map name={map} death={death} />
    </div>
  );
}

export default function Home() {
  const [ deaths, setDeaths ] = useState([]);

  useEffect(() => {
    axios.get('/data/deaths-stitched.json').then((response) => {
      console.log('Fetched deaths', response);
      setDeaths(response.data.split('\n').slice(0,-1).map(JSON.parse))
    }).catch((error) => {
      console.error('Failed to fetch data', error);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Death Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DeathForm deaths={deaths}/>
    </div>
  )
}
